################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    - &OrdererOrg
        Name: OrdererOrg
        ID: OrdererMSP
        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/logistics.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &OriginOrg
        Name: OriginOrgMSP
        ID: OriginOrgMSP
        MSPDir: crypto-config/peerOrganizations/origin.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OriginOrgMSP.admin', 'OriginOrgMSP.peer', 'OriginOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OriginOrgMSP.admin', 'OriginOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OriginOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('OriginOrgMSP.peer')"
        # AnchorPeers defines the location of peers which can be used for cross-org gossip
        AnchorPeers:
            - Host: origin-station.origin.com
              Port: 7051

    - &DestOrg
        Name: DestOrgMSP
        ID: DestOrgMSP
        MSPDir: crypto-config/peerOrganizations/dest.com/msp
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DestOrgMSP.admin', 'DestOrgMSP.peer', 'DestOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DestOrgMSP.admin', 'DestOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DestOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('DestOrgMSP.peer')"
        # AnchorPeers defines the location of peers which can be used for cross-org gossip
        AnchorPeers:
            - Host: dest-station.dest.com
              Port: 11051 # Assuming dest-station uses this port in your docker-compose

################################################################################
#
#   SECTION: Capabilities
#
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#
#   SECTION: Application
#
################################################################################
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        LifecycleEndorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#
#   SECTION: Orderer
#
################################################################################
Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
        - Host: orderer1.logistics.com
          Port: 7050
          ClientTLSCert: crypto-config/ordererOrganizations/logistics.com/orderers/orderer1.logistics.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/logistics.com/orderers/orderer1.logistics.com/tls/server.crt
        - Host: orderer2.logistics.com
          Port: 8050
          ClientTLSCert: crypto-config/ordererOrganizations/logistics.com/orderers/orderer2.logistics.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/logistics.com/orderers/orderer2.logistics.com/tls/server.crt
        - Host: orderer3.logistics.com
          Port: 9050
          ClientTLSCert: crypto-config/ordererOrganizations/logistics.com/orderers/orderer3.logistics.com/tls/server.crt
          ServerTLSCert: crypto-config/ordererOrganizations/logistics.com/orderers/orderer3.logistics.com/tls/server.crt
    Addresses:
        - orderer1.logistics.com:7050
        - orderer2.logistics.com:8050
        - orderer3.logistics.com:9050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

################################################################################
#
#   CHANNEL
#
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#
#   Profile
#
################################################################################
Profiles:
    LogisticsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            LogisticsConsortium:
                Organizations:
                    - *OriginOrg
                    - *DestOrg
    LogisticsChannel:
        Consortium: LogisticsConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *OriginOrg
                - *DestOrg
            Capabilities:
                <<: *ApplicationCapabilities
