
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of the ordering service organization
# ---------------------------------------------------------------------------
OrdererOrgs:
  - Name: Orderer
    Domain: logistics.com # A more relevant domain for the project
    EnableNodeOUs: true
    # Specs defines the list of ordering nodes.
    Specs:
      - Hostname: orderer1
        SANS:
          - "localhost"
      - Hostname: orderer2
        SANS:
          - "localhost"
      - Hostname: orderer3
        SANS:
          - "localhost"

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Org1: The Origin Country Consortium
  # ---------------------------------------------------------------------------
  - Name: OriginOrg
    Domain: origin.com # Domain for all entities in the origin country
    EnableNodeOUs: true
    # We use "Specs" instead of "Template" to define specific hostnames for our peers.
    Specs:
      - Hostname: origin-station
        SANS:
          - "localhost"
      - Hostname: origin-rail
        SANS:
          - "localhost"
      - Hostname: origin-customs
        SANS:
          - "localhost"
      - Hostname: origin-border
        SANS:
          - "localhost"
    # The number of non-admin user identities to generate for this organization
    Users:
      Count: 1

  # ---------------------------------------------------------------------------
  # Org2: The Destination Country Consortium
  # ---------------------------------------------------------------------------
  - Name: DestOrg
    Domain: dest.com # Domain for all entities in the destination country
    EnableNodeOUs: true
    # Defining the four specific peers for the destination country.
    Specs:
      - Hostname: dest-station
        SANS:
          - "localhost"
      - Hostname: dest-rail
        SANS:
          - "localhost"
      - Hostname: dest-customs
        SANS:
          - "localhost"
      - Hostname: dest-border
        SANS:
          - "localhost"
    # The number of non-admin user identities to generate for this organization
    Users:
      Count: 1
